-- Generated from src/data/seed-catalog.ts — do not hand-edit product rows here.
-- Re-run `node scripts/generate-seed-sql.ts` after changing the catalog source.

insert into shop_settings (shop_name, shop_description, whatsapp_number, currency)
values ('Electro Project Items', 'Components, tools, modules and project essentials — all in one place.', '919999999999', 'INR')
on conflict do nothing;

insert into categories (name, slug, icon) values
  ('Microcontrollers', 'microcontrollers', 'cpu'),
  ('Motors & Drivers', 'motors-drivers', 'cog'),
  ('Sensors', 'sensors', 'radar'),
  ('LEDs & Displays', 'leds-displays', 'lightbulb'),
  ('Switches & Controls', 'switches-controls', 'toggle-left'),
  ('Capacitors', 'capacitors', 'battery'),
  ('Resistors', 'resistors', 'zap'),
  ('Diodes', 'diodes', 'git-commit-horizontal'),
  ('Transistors', 'transistors', 'component'),
  ('ICs', 'ics', 'microchip'),
  ('Wires & Jumper Wires', 'wires-jumper-wires', 'cable'),
  ('PCBs & Breadboards', 'pcbs-breadboards', 'layout-grid'),
  ('Soldering & Tools', 'soldering-tools', 'wrench'),
  ('Batteries & Power', 'batteries-power', 'battery-charging'),
  ('Modules', 'modules', 'box'),
  ('Other Components', 'other-components', 'package')
on conflict (slug) do nothing;

insert into products (name, slug, price, category_id, is_featured) values
  ('7 Segment Display', '7-segment-display', 20, (select id from categories where slug = 'leds-displays'), false),
  ('Buzzer', 'buzzer', 35, (select id from categories where slug = 'modules'), false),
  ('IR Receiver', 'ir-receiver', 15, (select id from categories where slug = 'sensors'), false),
  ('Laser Module', 'laser-module', 50, (select id from categories where slug = 'modules'), false),
  ('Capacitor 10µF 35V', 'capacitor-10uf-35v', 5, (select id from categories where slug = 'capacitors'), false),
  ('Capacitor 100µF 35V', 'capacitor-100uf-35v', 5, (select id from categories where slug = 'capacitors'), false),
  ('Capacitor 220µF 35V', 'capacitor-220uf-35v', 5, (select id from categories where slug = 'capacitors'), false),
  ('ESP32 (38 Pin)', 'esp32-38-pin', 500, (select id from categories where slug = 'microcontrollers'), true),
  ('Multimeter Wire', 'multimeter-wire', 50, (select id from categories where slug = 'soldering-tools'), false),
  ('12V Coin Light', '12v-coin-light', 10, (select id from categories where slug = 'leds-displays'), false),
  ('Tiptop Switch', 'tiptop-switch', 10, (select id from categories where slug = 'switches-controls'), false),
  ('Iron Stand', 'iron-stand', 100, (select id from categories where slug = 'soldering-tools'), false),
  ('10K Potentiometer', '10k-potentiometer', 15, (select id from categories where slug = 'switches-controls'), false),
  ('Crocodile Clip', 'crocodile-clip', 15, (select id from categories where slug = 'wires-jumper-wires'), false),
  ('Potentiometer Knob', 'potentiometer-knob', 5, (select id from categories where slug = 'switches-controls'), false),
  ('DC Male/Female Wire Set', 'dc-male-female-wire-set', 30, (select id from categories where slug = 'wires-jumper-wires'), false),
  ('Male-to-Female Jumper Wire (1 pc)', 'male-to-female-jumper-wire-1-pc', 8, (select id from categories where slug = 'wires-jumper-wires'), false),
  ('9V NIPPO Battery', '9v-nippo-battery', 50, (select id from categories where slug = 'batteries-power'), false),
  ('LDR', 'ldr', 10, (select id from categories where slug = 'sensors'), false),
  ('775 Motor', '775-motor', 250, (select id from categories where slug = 'motors-drivers'), true),
  ('Cutter', 'cutter', 60, (select id from categories where slug = 'soldering-tools'), false),
  ('4×4 PCB', '4x4-pcb', 50, (select id from categories where slug = 'pcbs-breadboards'), false),
  ('2×6 PCB', '2x6-pcb', 70, (select id from categories where slug = 'pcbs-breadboards'), false),
  ('1-Core Black Wire (1 m)', '1-core-black-wire-1-m', 20, (select id from categories where slug = 'wires-jumper-wires'), false),
  ('1-Core Red Wire (1 m)', '1-core-red-wire-1-m', 20, (select id from categories where slug = 'wires-jumper-wires'), false),
  ('Soldering Wire Set', 'soldering-wire-set', 150, (select id from categories where slug = 'soldering-tools'), false),
  ('Soldering Wire (1 m)', 'soldering-wire-1-m', 30, (select id from categories where slug = 'soldering-tools'), false),
  ('Soldering Iron', 'soldering-iron', 150, (select id from categories where slug = 'soldering-tools'), false),
  ('Mini Resistor Box', 'mini-resistor-box', 60, (select id from categories where slug = 'resistors'), false),
  ('0–12V Transformer', '0-12v-transformer', 125, (select id from categories where slug = 'batteries-power'), false),
  ('9V Battery Cap', '9v-battery-cap', 5, (select id from categories where slug = 'batteries-power'), false),
  ('1N4007 Diode', '1n4007-diode', 5, (select id from categories where slug = 'diodes'), false),
  ('5V1 Diode', '5v1-diode', 5, (select id from categories where slug = 'diodes'), false),
  ('8V2 Diode', '8v2-diode', 5, (select id from categories where slug = 'diodes'), false),
  ('Micro Push Button', 'micro-push-button', 5, (select id from categories where slug = 'switches-controls'), false),
  ('Slide Switch', 'slide-switch', 10, (select id from categories where slug = 'switches-controls'), false),
  ('Normal Switch', 'normal-switch', 7, (select id from categories where slug = 'switches-controls'), false),
  ('SG90 Micro Servo Motor', 'sg90-micro-servo-motor', 150, (select id from categories where slug = 'motors-drivers'), true),
  ('L298N Motor Driver / Servo Shield', 'l298n-motor-driver-servo-shield', 250, (select id from categories where slug = 'motors-drivers'), true),
  ('2N2222A Transistor', '2n2222a-transistor', 5, (select id from categories where slug = 'transistors'), false),
  ('BC547 Transistor', 'bc547-transistor', 5, (select id from categories where slug = 'transistors'), false),
  ('BC557 Transistor', 'bc557-transistor', 5, (select id from categories where slug = 'transistors'), false),
  ('IC 741', 'ic-741', 20, (select id from categories where slug = 'ics'), false),
  ('IC 746', 'ic-746', 20, (select id from categories where slug = 'ics'), false),
  ('IC 7485', 'ic-7485', 30, (select id from categories where slug = 'ics'), false),
  ('IC 7486', 'ic-7486', 20, (select id from categories where slug = 'ics'), false),
  ('IC 7432', 'ic-7432', 20, (select id from categories where slug = 'ics'), false),
  ('IC 7408', 'ic-7408', 20, (select id from categories where slug = 'ics'), false),
  ('IC 7404', 'ic-7404', 20, (select id from categories where slug = 'ics'), false),
  ('IC 7402', 'ic-7402', 20, (select id from categories where slug = 'ics'), false),
  ('IC 7400', 'ic-7400', 20, (select id from categories where slug = 'ics'), false),
  ('Big Breadboard', 'big-breadboard', 100, (select id from categories where slug = 'pcbs-breadboards'), true),
  ('Mid Breadboard', 'mid-breadboard', 70, (select id from categories where slug = 'pcbs-breadboards'), false),
  ('Small Breadboard', 'small-breadboard', 30, (select id from categories where slug = 'pcbs-breadboards'), false),
  ('Preset 5K', 'preset-5k', 10, (select id from categories where slug = 'resistors'), false),
  ('Preset 10K', 'preset-10k', 10, (select id from categories where slug = 'resistors'), false),
  ('Multimeter', 'multimeter', 200, (select id from categories where slug = 'soldering-tools'), true),
  ('All Type Resistor', 'all-type-resistor', 2, (select id from categories where slug = 'resistors'), false),
  ('All Type LED', 'all-type-led', 2, (select id from categories where slug = 'leds-displays'), false),
  ('Male-to-Male Jumper Wire (1 pc)', 'male-to-male-jumper-wire-1-pc', 3, (select id from categories where slug = 'wires-jumper-wires'), false)
on conflict (slug) do nothing;

